name: build
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > /home/runner/keystore
          cat /home/runner/keystore
          fastlane build
      - uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/traccar/release/sms-messenger-traccar-release-unsigned.apk
      - uses: actions/upload-pages-artifact@v2
        with:
          path: app/build/outputs/apk/traccar/release/sms-messenger-traccar-release-unsigned.apk
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/jcardus/traccar-sms-gateway/releases/1"
          asset_path: app/build/outputs/apk/traccar/release/sms-messenger-traccar-release-unsigned.apk
          asset_name: app
          asset_content_type: application/zip

