name: build
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > /home/runner/keystore
          fastlane build
      - uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/traccar/release/sms-messenger-traccar-release.apk
      - name: Deploy to Pages
        run: |
            mkdir -p public
            mv app/build/outputs/apk/traccar/release/sms-messenger-traccar-release.apk public/
            echo "Download the APK from the link below:" > public/index.html
            echo "<a href='sms-messenger-traccar-release.apk'>Download APK</a>" >> public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/fleetmap-io/traccar-sms-gateway/releases/1"
          asset_path: public/sms-messenger-traccar-release.apk
          asset_name: app
          asset_content_type: application/zip

