name: build
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: fastlane build
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/jcardus/traccar-sms-gateway/releases/1
          asset_path: ./app/build/outputs/apk/traccar/release
          asset_name: sms-messenger-traccar-release-unsigned.apk
          asset_content_type: application/vnd.android.package-archive

