name: Deploy to pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    env:
      VERSION_NAME: "6.0"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: $VERSION_NAME
      - run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > /home/runner/keystore
          echo "auth.token=${{ secrets.SENTRY_AUTH_TOKEN }}" >> sentry.properties            
          fastlane build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - run: |
            mkdir -pv public
            mv -v app/build/outputs/apk/traccar/release/sms-messenger-traccar-release.apk "public/fleetmap-sms-$VERSION_NAME.apk"
            echo "Download the APK $VERSION_NAME from the link below:" > public/index.html
            echo "<a href='fleetmap-sms-$VERSION_NAME.apk'>Download APK</a>" >> public/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
